version: '3.6'
services:

    cloud-registry:
        image: elixircloud/csh:0.1.0
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"